### ISSUE TITLE
Wrong Up/Down speed / possibility to change the units

### ISSUE THREAD

**Issue by Jannomag** [Jbcbro/qBitRemote-Public#1]
Hi,
since BarMagnet doesn't work for me I was trying your app.
It works great and does what a torrent remote should do.

But I would like to have MB or GB instead of KB under each torrent.

Also, the Upload and Download Speed in the top left corner are wrong. See the screenshots:
![image](https://user-images.githubusercontent.com/31586674/147659746-c644819e-479a-4f8f-b747-6c3ae5010e40.jpeg)
![image](https://user-images.githubusercontent.com/31586674/147659749-45752d7e-985f-4bb9-a129-8d488433c3ad.jpeg)

**Comment by Jbcbro** [comment]
Yeah, the left top is just randomly generated numbers.
I will update this weekend and make a setting for KB, MB or GB/s.

(I can also see i need to change the background on the text)
