### ISSUE TITLE
Alert: Could not auth with server

### ISSUE THREAD

**Issue by toledobastos** [Jbcbro/qBitRemote-Public#7]
Any idea what may be causing the failure to authenticate? I changed from SSL to http, changed username and password, change certificates, etc. Nothing will do. The app won't authenticate.

I can open qbittorrent on the browser without any problems. It's just the app that won't talk to the server.

**Comment by Jbcbro** [comment]
I could be tjat you are writing your username with first letter as capital.

**Comment by toledobastos** [comment]
Got it to authenticate after changing from SSL to http and back a few times. Also changed the login account. That seems to have done the trick.

**Comment by toledobastos** [comment]
> I could be that you are writing your username with first letter as capital.

nah, it wasn't that. It was something else. Very strange.

**Comment by HeyMeco** [comment]
I also have this error, what did you do to fix it?

**Comment by toledobastos** [comment]
I gave up on it. I've been using Transmissionic since.

**Comment by Jbcbro** [comment]
The issue will be addressed in the next release.
It was due to a change in authentication in the qbittorrent API.

@toledobastos @HeyMeco

**Comment by illuvattarr** [comment]
I still have this problem on ios with the newest  version. I cant login even though my credentials work when connecting through safari.

**Comment by Jbcbro** [comment]
What version are you running og qbittorrent?
