### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ronad666** [Jbcbro/qBitRemote-Public#8]
I recently added QBitremote via Altserver onto my iPhone SE. This is the screen I get when I open it.
![IMG_2027](https://user-images.githubusercontent.com/102882982/161404400-4ed4dbe0-5aa6-4f7c-a723-c26bbfb1f664.png). What am I doing wrong?

**Comment by Jbcbro** [comment]
Did you configure it in the settings tab?

**Comment by Jbcbro** [comment]
Issue has been fixed in latest release
